image: docker:20.10
variables: 
DOCKER_TLS_CERTDIR: ""
DOCKER_DRIVER: overlay2
services
:
- docker:20.10
-dind
build
-master:
tags: - docker
stage: build
script
:
- docker build
-t myimage
.
only
:
- master

stages:
  - build

build_job:
  stage: build
  script:
    - echo "Building the project..."


build-npm:
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    stage: build
    image: node:lts-alpine
    variables:
      PRODUCTION: "true"
    script:
        - npm install
        - npm run build
