name: Docker Build & Push

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  build-master:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.repository }}
      
    - name: Login to Container Registry
      run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin

    - name: Build Docker Image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ steps.string.outputs.lowercase }}:latest .

    - name: Push Docker Image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ steps.string.outputs.lowercase }}:latest


